// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

/*
Package usercmd is a generated protocol buffer package.

It is generated from these files:
	base.proto

It has these top-level messages:
	LoginC2SMsg
	LoginS2CMsg
	IntoRoomC2SMsg
	IntoRoomS2CMsg
	BattleEntity
	SyncAllBattleEntitiesS2CMsg
	TurnInfoS2CMsg
	CastSkillC2SMsg
	SkillResultS2CMsg
*/
package usercmd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CmdType int32

const (
	CmdType_LoginReq              CmdType = 0
	CmdType_LoginRes              CmdType = 1
	CmdType_IntoRoomReq           CmdType = 2
	CmdType_IntoRoomRes           CmdType = 3
	CmdType_SyncAllBattleEntities CmdType = 4
	CmdType_TurnInfo              CmdType = 5
	CmdType_CastSkillReq          CmdType = 6
	CmdType_SkillResultRes        CmdType = 7
	CmdType_MaxCmdId              CmdType = 8
)

var CmdType_name = map[int32]string{
	0: "LoginReq",
	1: "LoginRes",
	2: "IntoRoomReq",
	3: "IntoRoomRes",
	4: "SyncAllBattleEntities",
	5: "TurnInfo",
	6: "CastSkillReq",
	7: "SkillResultRes",
	8: "MaxCmdId",
}
var CmdType_value = map[string]int32{
	"LoginReq":              0,
	"LoginRes":              1,
	"IntoRoomReq":           2,
	"IntoRoomRes":           3,
	"SyncAllBattleEntities": 4,
	"TurnInfo":              5,
	"CastSkillReq":          6,
	"SkillResultRes":        7,
	"MaxCmdId":              8,
}

func (x CmdType) String() string {
	return proto.EnumName(CmdType_name, int32(x))
}
func (CmdType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PosIndex int32

const (
	PosIndex_PosELeft   PosIndex = 0
	PosIndex_PosECenter PosIndex = 1
	PosIndex_PosERight  PosIndex = 2
	PosIndex_PosBLeft   PosIndex = 3
	PosIndex_PosBCenter PosIndex = 4
	PosIndex_PosBRight  PosIndex = 5
)

var PosIndex_name = map[int32]string{
	0: "PosELeft",
	1: "PosECenter",
	2: "PosERight",
	3: "PosBLeft",
	4: "PosBCenter",
	5: "PosBRight",
}
var PosIndex_value = map[string]int32{
	"PosELeft":   0,
	"PosECenter": 1,
	"PosERight":  2,
	"PosBLeft":   3,
	"PosBCenter": 4,
	"PosBRight":  5,
}

func (x PosIndex) String() string {
	return proto.EnumName(PosIndex_name, int32(x))
}
func (PosIndex) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type LoginC2SMsg struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *LoginC2SMsg) Reset()                    { *m = LoginC2SMsg{} }
func (m *LoginC2SMsg) String() string            { return proto.CompactTextString(m) }
func (*LoginC2SMsg) ProtoMessage()               {}
func (*LoginC2SMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginC2SMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginS2CMsg struct {
	PlayerId uint32 `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
}

func (m *LoginS2CMsg) Reset()                    { *m = LoginS2CMsg{} }
func (m *LoginS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*LoginS2CMsg) ProtoMessage()               {}
func (*LoginS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginS2CMsg) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type IntoRoomC2SMsg struct {
}

func (m *IntoRoomC2SMsg) Reset()                    { *m = IntoRoomC2SMsg{} }
func (m *IntoRoomC2SMsg) String() string            { return proto.CompactTextString(m) }
func (*IntoRoomC2SMsg) ProtoMessage()               {}
func (*IntoRoomC2SMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type IntoRoomS2CMsg struct {
	RoomId uint32 `protobuf:"varint,1,opt,name=RoomId" json:"RoomId,omitempty"`
}

func (m *IntoRoomS2CMsg) Reset()                    { *m = IntoRoomS2CMsg{} }
func (m *IntoRoomS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*IntoRoomS2CMsg) ProtoMessage()               {}
func (*IntoRoomS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IntoRoomS2CMsg) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type BattleEntity struct {
	PosIndex       uint32 `protobuf:"varint,1,opt,name=PosIndex" json:"PosIndex,omitempty"`
	EntityType     uint32 `protobuf:"varint,2,opt,name=EntityType" json:"EntityType,omitempty"`
	Health         uint32 `protobuf:"varint,3,opt,name=Health" json:"Health,omitempty"`
	PhysicalAttack uint32 `protobuf:"varint,4,opt,name=PhysicalAttack" json:"PhysicalAttack,omitempty"`
	MagicAttack    uint32 `protobuf:"varint,5,opt,name=MagicAttack" json:"MagicAttack,omitempty"`
	PhysicalDefend uint32 `protobuf:"varint,6,opt,name=PhysicalDefend" json:"PhysicalDefend,omitempty"`
	MagicDefend    uint32 `protobuf:"varint,7,opt,name=MagicDefend" json:"MagicDefend,omitempty"`
	MoveSpeed      uint32 `protobuf:"varint,8,opt,name=MoveSpeed" json:"MoveSpeed,omitempty"`
}

func (m *BattleEntity) Reset()                    { *m = BattleEntity{} }
func (m *BattleEntity) String() string            { return proto.CompactTextString(m) }
func (*BattleEntity) ProtoMessage()               {}
func (*BattleEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BattleEntity) GetPosIndex() uint32 {
	if m != nil {
		return m.PosIndex
	}
	return 0
}

func (m *BattleEntity) GetEntityType() uint32 {
	if m != nil {
		return m.EntityType
	}
	return 0
}

func (m *BattleEntity) GetHealth() uint32 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *BattleEntity) GetPhysicalAttack() uint32 {
	if m != nil {
		return m.PhysicalAttack
	}
	return 0
}

func (m *BattleEntity) GetMagicAttack() uint32 {
	if m != nil {
		return m.MagicAttack
	}
	return 0
}

func (m *BattleEntity) GetPhysicalDefend() uint32 {
	if m != nil {
		return m.PhysicalDefend
	}
	return 0
}

func (m *BattleEntity) GetMagicDefend() uint32 {
	if m != nil {
		return m.MagicDefend
	}
	return 0
}

func (m *BattleEntity) GetMoveSpeed() uint32 {
	if m != nil {
		return m.MoveSpeed
	}
	return 0
}

type SyncAllBattleEntitiesS2CMsg struct {
	Entities []*BattleEntity `protobuf:"bytes,1,rep,name=entities" json:"entities,omitempty"`
}

func (m *SyncAllBattleEntitiesS2CMsg) Reset()                    { *m = SyncAllBattleEntitiesS2CMsg{} }
func (m *SyncAllBattleEntitiesS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*SyncAllBattleEntitiesS2CMsg) ProtoMessage()               {}
func (*SyncAllBattleEntitiesS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SyncAllBattleEntitiesS2CMsg) GetEntities() []*BattleEntity {
	if m != nil {
		return m.Entities
	}
	return nil
}

type TurnInfoS2CMsg struct {
	BigTurnIndex      uint32   `protobuf:"varint,1,opt,name=BigTurnIndex" json:"BigTurnIndex,omitempty"`
	SmallTurnIndex    uint32   `protobuf:"varint,2,opt,name=SmallTurnIndex" json:"SmallTurnIndex,omitempty"`
	CurEntityPosIndex uint32   `protobuf:"varint,3,opt,name=CurEntityPosIndex" json:"CurEntityPosIndex,omitempty"`
	SkillSet          []uint32 `protobuf:"varint,4,rep,packed,name=SkillSet" json:"SkillSet,omitempty"`
}

func (m *TurnInfoS2CMsg) Reset()                    { *m = TurnInfoS2CMsg{} }
func (m *TurnInfoS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*TurnInfoS2CMsg) ProtoMessage()               {}
func (*TurnInfoS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TurnInfoS2CMsg) GetBigTurnIndex() uint32 {
	if m != nil {
		return m.BigTurnIndex
	}
	return 0
}

func (m *TurnInfoS2CMsg) GetSmallTurnIndex() uint32 {
	if m != nil {
		return m.SmallTurnIndex
	}
	return 0
}

func (m *TurnInfoS2CMsg) GetCurEntityPosIndex() uint32 {
	if m != nil {
		return m.CurEntityPosIndex
	}
	return 0
}

func (m *TurnInfoS2CMsg) GetSkillSet() []uint32 {
	if m != nil {
		return m.SkillSet
	}
	return nil
}

type CastSkillC2SMsg struct {
	SkillId   uint32   `protobuf:"varint,1,opt,name=SkillId" json:"SkillId,omitempty"`
	TargetIds []uint32 `protobuf:"varint,2,rep,packed,name=TargetIds" json:"TargetIds,omitempty"`
}

func (m *CastSkillC2SMsg) Reset()                    { *m = CastSkillC2SMsg{} }
func (m *CastSkillC2SMsg) String() string            { return proto.CompactTextString(m) }
func (*CastSkillC2SMsg) ProtoMessage()               {}
func (*CastSkillC2SMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CastSkillC2SMsg) GetSkillId() uint32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *CastSkillC2SMsg) GetTargetIds() []uint32 {
	if m != nil {
		return m.TargetIds
	}
	return nil
}

type SkillResultS2CMsg struct {
}

func (m *SkillResultS2CMsg) Reset()                    { *m = SkillResultS2CMsg{} }
func (m *SkillResultS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*SkillResultS2CMsg) ProtoMessage()               {}
func (*SkillResultS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*LoginC2SMsg)(nil), "usercmd.LoginC2SMsg")
	proto.RegisterType((*LoginS2CMsg)(nil), "usercmd.LoginS2CMsg")
	proto.RegisterType((*IntoRoomC2SMsg)(nil), "usercmd.IntoRoomC2SMsg")
	proto.RegisterType((*IntoRoomS2CMsg)(nil), "usercmd.IntoRoomS2cMsg")
	proto.RegisterType((*BattleEntity)(nil), "usercmd.BattleEntity")
	proto.RegisterType((*SyncAllBattleEntitiesS2CMsg)(nil), "usercmd.SyncAllBattleEntitiesS2CMsg")
	proto.RegisterType((*TurnInfoS2CMsg)(nil), "usercmd.TurnInfoS2CMsg")
	proto.RegisterType((*CastSkillC2SMsg)(nil), "usercmd.CastSkillC2SMsg")
	proto.RegisterType((*SkillResultS2CMsg)(nil), "usercmd.SkillResultS2CMsg")
	proto.RegisterEnum("usercmd.CmdType", CmdType_name, CmdType_value)
	proto.RegisterEnum("usercmd.PosIndex", PosIndex_name, PosIndex_value)
}

func init() { proto.RegisterFile("base.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xeb, 0x6e, 0xda, 0x4e,
	0x10, 0xc5, 0x63, 0x20, 0x40, 0x06, 0x42, 0x9c, 0xfd, 0x2b, 0x7f, 0xb9, 0x17, 0x55, 0xd4, 0x1f,
	0x2a, 0x1a, 0x55, 0x48, 0xa5, 0x4f, 0x10, 0xdc, 0x48, 0xb5, 0x14, 0x24, 0x64, 0xf3, 0x02, 0x1b,
	0x7b, 0x30, 0x56, 0xd6, 0x36, 0xf5, 0x2e, 0x55, 0x78, 0x8f, 0x3e, 0x42, 0xd5, 0xe7, 0xac, 0xf6,
	0xe2, 0x0b, 0x69, 0xbf, 0x71, 0xce, 0xfc, 0xf6, 0x2c, 0x3b, 0x33, 0x00, 0xf0, 0x48, 0x39, 0xce,
	0xf7, 0x65, 0x21, 0x0a, 0x32, 0x38, 0x70, 0x2c, 0xa3, 0x2c, 0x76, 0xdf, 0xc3, 0xe8, 0xa1, 0x48,
	0xd2, 0xdc, 0x5b, 0x84, 0x2b, 0x9e, 0x10, 0x02, 0xbd, 0x9c, 0x66, 0xe8, 0x58, 0x53, 0x6b, 0x76,
	0x11, 0xa8, 0xcf, 0xee, 0x47, 0x83, 0x84, 0x0b, 0x4f, 0x22, 0xaf, 0x61, 0xb8, 0x67, 0xf4, 0x88,
	0xa5, 0x1f, 0x2b, 0xec, 0x32, 0xa8, 0xb5, 0x6b, 0xc3, 0xc4, 0xcf, 0x45, 0x11, 0x14, 0x45, 0xa6,
	0x03, 0xdd, 0x59, 0xe3, 0x84, 0x8b, 0x48, 0x9e, 0xff, 0x1f, 0xfa, 0x52, 0xd5, 0xa7, 0x8d, 0x72,
	0x7f, 0x76, 0x60, 0xbc, 0xa4, 0x42, 0x30, 0xbc, 0xcf, 0x45, 0x2a, 0x8e, 0xf2, 0xa2, 0x75, 0xc1,
	0xfd, 0x3c, 0xc6, 0xe7, 0xea, 0xa2, 0x4a, 0x93, 0x77, 0x00, 0x9a, 0xda, 0x1c, 0xf7, 0xe8, 0x74,
	0x54, 0xb5, 0xe5, 0xc8, 0x4b, 0xbe, 0x21, 0x65, 0x62, 0xe7, 0x74, 0xf5, 0x25, 0x5a, 0x91, 0x0f,
	0x30, 0x59, 0xef, 0x8e, 0x3c, 0x8d, 0x28, 0xbb, 0x13, 0x82, 0x46, 0x4f, 0x4e, 0x4f, 0xd5, 0x5f,
	0xb8, 0x64, 0x0a, 0xa3, 0x15, 0x4d, 0xd2, 0xc8, 0x40, 0xe7, 0x0a, 0x6a, 0x5b, 0xed, 0xa4, 0xaf,
	0xb8, 0xc5, 0x3c, 0x76, 0xfa, 0xa7, 0x49, 0xda, 0xad, 0x93, 0x0c, 0x34, 0x68, 0x25, 0x19, 0xe2,
	0x2d, 0x5c, 0xac, 0x8a, 0x1f, 0x18, 0xee, 0x11, 0x63, 0x67, 0xa8, 0xea, 0x8d, 0xe1, 0xae, 0xe1,
	0x4d, 0x78, 0xcc, 0xa3, 0x3b, 0xc6, 0x5a, 0xcd, 0x49, 0x91, 0x9b, 0x69, 0x7c, 0x86, 0x21, 0x1a,
	0xc7, 0xb1, 0xa6, 0xdd, 0xd9, 0x68, 0x71, 0x33, 0x37, 0xb3, 0x9d, 0xb7, 0xbb, 0x19, 0xd4, 0x98,
	0xfb, 0xdb, 0x82, 0xc9, 0xe6, 0x50, 0xe6, 0x7e, 0xbe, 0x2d, 0x4c, 0x8a, 0x0b, 0xe3, 0x65, 0x9a,
	0x68, 0xb3, 0x69, 0xf7, 0x89, 0x27, 0x1f, 0x1c, 0x66, 0x94, 0xb1, 0x86, 0xd2, 0x6d, 0x7f, 0xe1,
	0x92, 0x4f, 0x70, 0xed, 0x1d, 0x4a, 0x7d, 0x6b, 0x3d, 0x3f, 0x3d, 0x85, 0xbf, 0x0b, 0x72, 0xc8,
	0xe1, 0x53, 0xca, 0x58, 0x88, 0xc2, 0xe9, 0x4d, 0xbb, 0x72, 0xc8, 0x95, 0x76, 0x7d, 0xb8, 0xf2,
	0x28, 0x17, 0x4a, 0x9b, 0xfd, 0x74, 0x60, 0xa0, 0x64, 0xbd, 0x3d, 0x95, 0x94, 0x5d, 0xdc, 0xd0,
	0x32, 0x41, 0xe1, 0xc7, 0xdc, 0xe9, 0xa8, 0xa4, 0xc6, 0x70, 0xff, 0x83, 0x6b, 0x05, 0x06, 0xc8,
	0x0f, 0x4c, 0xe8, 0x57, 0xdf, 0xfe, 0xb2, 0x60, 0xe0, 0x65, 0xb1, 0x5a, 0x98, 0x31, 0x0c, 0xd5,
	0x92, 0x07, 0xf8, 0xdd, 0x3e, 0x6b, 0x29, 0x6e, 0x5b, 0xe4, 0x0a, 0x46, 0xd5, 0x0e, 0xcb, 0x72,
	0xe7, 0xd4, 0xe0, 0x76, 0x97, 0xbc, 0x82, 0x9b, 0x7f, 0x0e, 0xc9, 0xee, 0xc9, 0xa8, 0xaa, 0xd9,
	0xf6, 0x39, 0xb1, 0x61, 0x5c, 0x3f, 0x49, 0x66, 0xf5, 0x09, 0x81, 0x49, 0xeb, 0x9b, 0xc9, 0xb8,
	0x81, 0x3c, 0xb3, 0xa2, 0xcf, 0x5e, 0x16, 0xfb, 0xb1, 0x3d, 0xbc, 0x8d, 0x9b, 0xdf, 0x81, 0xac,
	0xac, 0x0b, 0x7e, 0xff, 0x80, 0x5b, 0x61, 0x9f, 0x91, 0x09, 0x80, 0x54, 0x1e, 0xe6, 0x02, 0x4b,
	0xdb, 0x22, 0x97, 0x70, 0x21, 0x75, 0x90, 0x26, 0x3b, 0x61, 0x77, 0x0c, 0xbc, 0x54, 0x70, 0xd7,
	0xc0, 0x4b, 0x03, 0xf7, 0x0c, 0xbc, 0xd4, 0xf0, 0xf9, 0x63, 0x5f, 0xfd, 0x31, 0x7c, 0xf9, 0x13,
	0x00, 0x00, 0xff, 0xff, 0xdc, 0x21, 0xb3, 0x81, 0x26, 0x04, 0x00, 0x00,
}
